"""Raw Effects identifiers — the complete catalog from Blizzard's stableid.json.

DO NOT EDIT. Generated by `tools/generate_ids.py`. Curate names in `sc2nachos/ids/effect.py` instead.
"""

from sc2nachos.ids._base import ReadableIntEnum


class RawEffectId(ReadableIntEnum):
    """Every effect id the game defines, named as Blizzard names it."""

    Null = 0
    PsiStormPersistent = 1
    GuardianShieldPersistent = 2
    TemporalFieldGrowingBubbleCreatePersistent = 3
    TemporalFieldAfterBubbleCreatePersistent = 4
    ThermalLancesForward = 5
    ScannerSweep = 6
    NukePersistent = 7
    LiberatorTargetMorphDelayPersistent = 8
    LiberatorTargetMorphPersistent = 9
    BlindingCloudCP = 10
    RavagerCorrosiveBileCP = 11
    LurkerMP = 12
