"""The events the api hands out as a game goes on, and the bus that hands them to handlers.

A game hands out `GameStartEvent`, then a turn for each observation but the last, then `GameEndEvent`. A turn hands
out `TurnStartEvent`, then the events its observation reports, then `TurnEvent`. `only`, `of` and `where` select some
events of a type. `UnitEvent`, `BuffEvent`, `VitalEvent` and `AreaEvent` are bases through which a handler takes a
whole kind of event. A subclass of `Event` is a bot's own event, sent with `EventBus.emit`. `docs/events.md` lists
every event: its fields, what selects it, and when it comes.
"""

from sc2nachos.events._done import Done
from sc2nachos.events._event import (
    AlertEvent,
    AreaEvent,
    BuffEvent,
    ChatEvent,
    EnemyUnitCloakChangedEvent,
    EnemyUnitDamagedEvent,
    EnemyUnitEnergyLostEvent,
    EnemyUnitEnteredAreaEvent,
    EnemyUnitEnteredSightEvent,
    EnemyUnitFirstSeenEvent,
    EnemyUnitGainedBuffEvent,
    EnemyUnitLeftAreaEvent,
    EnemyUnitLeftSightEvent,
    EnemyUnitLostBuffEvent,
    EnemyUnitVitalDroppedEvent,
    EnemyUnitVitalReachedEvent,
    Event,
    GameEndEvent,
    GameStartEvent,
    OwnActionEvent,
    OwnConstructionFinishedEvent,
    OwnConstructionStartedEvent,
    OwnUnitCloakChangedEvent,
    OwnUnitCreatedEvent,
    OwnUnitDamagedEvent,
    OwnUnitEnergyLostEvent,
    OwnUnitEnteredAreaEvent,
    OwnUnitGainedBuffEvent,
    OwnUnitLeftAreaEvent,
    OwnUnitLostBuffEvent,
    OwnUnitVitalDroppedEvent,
    OwnUnitVitalReachedEvent,
    OwnUpgradeFinishedEvent,
    OwnWarpInFinishedEvent,
    ParameterizedEvent,
    TurnEvent,
    TurnStartEvent,
    UnitAllianceChangedEvent,
    UnitDiedEvent,
    UnitEvent,
    UnitFoundDeadEvent,
    UnitTypeChangedEvent,
    VitalEvent,
)
from sc2nachos.events._event_bus import EventBus
from sc2nachos.events._event_filter import EventFilter
from sc2nachos.events._event_priority import EventPriority
from sc2nachos.events._handler_timing import HandlerTiming

__all__ = [
    "AlertEvent",
    "AreaEvent",
    "BuffEvent",
    "ChatEvent",
    "Done",
    "EnemyUnitCloakChangedEvent",
    "EnemyUnitDamagedEvent",
    "EnemyUnitEnergyLostEvent",
    "EnemyUnitEnteredAreaEvent",
    "EnemyUnitEnteredSightEvent",
    "EnemyUnitFirstSeenEvent",
    "EnemyUnitGainedBuffEvent",
    "EnemyUnitLeftAreaEvent",
    "EnemyUnitLeftSightEvent",
    "EnemyUnitLostBuffEvent",
    "EnemyUnitVitalDroppedEvent",
    "EnemyUnitVitalReachedEvent",
    "Event",
    "EventBus",
    "EventFilter",
    "EventPriority",
    "GameEndEvent",
    "GameStartEvent",
    "HandlerTiming",
    "OwnActionEvent",
    "OwnConstructionFinishedEvent",
    "OwnConstructionStartedEvent",
    "OwnUnitCloakChangedEvent",
    "OwnUnitCreatedEvent",
    "OwnUnitDamagedEvent",
    "OwnUnitEnergyLostEvent",
    "OwnUnitEnteredAreaEvent",
    "OwnUnitGainedBuffEvent",
    "OwnUnitLeftAreaEvent",
    "OwnUnitLostBuffEvent",
    "OwnUnitVitalDroppedEvent",
    "OwnUnitVitalReachedEvent",
    "OwnUpgradeFinishedEvent",
    "OwnWarpInFinishedEvent",
    "ParameterizedEvent",
    "TurnEvent",
    "TurnStartEvent",
    "UnitAllianceChangedEvent",
    "UnitDiedEvent",
    "UnitEvent",
    "UnitFoundDeadEvent",
    "UnitTypeChangedEvent",
    "VitalEvent",
]
