"""Every type of unit, and the groups the game's tables put them in, as classes for the type checker.

DO NOT EDIT. Generated by `tools/generate_unit_types.py`; run it again after changing `UnitTypeId`.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, ClassVar, Self, TypeGuard, cast, overload

from sc2nachos.ids import UnitTypeId

if TYPE_CHECKING:
    from sc2nachos.units._own_unit import OwnUnit
    from sc2nachos.units._unit import Unit


class UnitType:
    """Every type of unit, and every group of types, for the type checker. None is ever instantiated.

    `Unit[UnitType.Marine]` is a marine, and `Unit[UnitType.ProtossStructure]` a Protoss structure. A type's `id` is
    its `UnitTypeId`. A group is a race, the structures, or the structures of a race, as the game's tables give them.
    """

    class AnyType:
        """Any type of unit, and what every type and group is.

        `type[UnitType.AnyType]` takes any of them. `Unit[Any]` is a unit that reads as any type, where
        `Unit[UnitType.AnyType]` is one whose type the type checker does not know, so a read only some types have is an
        error on it until `includes` narrows it.
        """

        _type_ids: ClassVar[frozenset[UnitTypeId]] = frozenset()

        def __init_subclass__(cls) -> None:
            """Add the type a class names by its `id` to every group it is in. A class without an `id` is a group."""
            super().__init_subclass__()
            type_id: UnitTypeId | None = cls.__dict__.get("id")
            cls._type_ids = frozenset() if type_id is None else frozenset((type_id,))
            if type_id is not None:
                # Everything between the class and `object` is a group it is in, `AnyType` included.
                for group in cast("tuple[type[UnitType.AnyType], ...]", cls.__mro__[1:-1]):
                    group._type_ids |= cls._type_ids

        @overload
        @classmethod
        def includes(cls, unit: OwnUnit[Any], /) -> TypeGuard[OwnUnit[Self]]: ...

        @overload
        @classmethod
        def includes(cls, unit: Unit[Any], /) -> TypeGuard[Unit[Self]]: ...

        @classmethod
        def includes(cls, unit: Unit[Any], /) -> bool:
            """Whether `unit` is of this type, or of a type in this group, narrowing it for the type checker.

            Raises `UncuratedIdError` for a unit of a type the curated ids leave out.
            """
            return unit.type_id in cls._type_ids

    class Structure(AnyType):
        """A type the game's tables give the structure attribute."""

    class Terran(AnyType):
        """A Terran type."""

    class Zerg(AnyType):
        """A Zerg type."""

    class Protoss(AnyType):
        """A Protoss type."""

    class TerranStructure(Terran, Structure):
        """A Terran structure."""

    class ZergStructure(Zerg, Structure):
        """A Zerg structure."""

    class ProtossStructure(Protoss, Structure):
        """A Protoss structure."""

    class AccelerationZoneFlyingLarge(Structure):
        id = UnitTypeId.ACCELERATION_ZONE_FLYING_LARGE

    class AccelerationZoneFlyingMedium(Structure):
        id = UnitTypeId.ACCELERATION_ZONE_FLYING_MEDIUM

    class AccelerationZoneFlyingSmall(Structure):
        id = UnitTypeId.ACCELERATION_ZONE_FLYING_SMALL

    class AccelerationZoneLarge(Structure):
        id = UnitTypeId.ACCELERATION_ZONE_LARGE

    class AccelerationZoneMedium(Structure):
        id = UnitTypeId.ACCELERATION_ZONE_MEDIUM

    class AccelerationZoneSmall(Structure):
        id = UnitTypeId.ACCELERATION_ZONE_SMALL

    class Adept(Protoss):
        id = UnitTypeId.ADEPT

    class AdeptShade(Protoss):
        id = UnitTypeId.ADEPT_SHADE

    class Archon(Protoss):
        id = UnitTypeId.ARCHON

    class Armory(TerranStructure):
        id = UnitTypeId.ARMORY

    class Assimilator(ProtossStructure):
        id = UnitTypeId.ASSIMILATOR

    class AssimilatorRich(ProtossStructure):
        id = UnitTypeId.ASSIMILATOR_RICH

    class AutoTurret(TerranStructure):
        id = UnitTypeId.AUTO_TURRET

    class Baneling(Zerg):
        id = UnitTypeId.BANELING

    class BanelingBurrowed(Zerg):
        id = UnitTypeId.BANELING_BURROWED

    class BanelingCocoon(Zerg):
        id = UnitTypeId.BANELING_COCOON

    class BanelingNest(ZergStructure):
        id = UnitTypeId.BANELING_NEST

    class Banshee(Terran):
        id = UnitTypeId.BANSHEE

    class Barracks(TerranStructure):
        id = UnitTypeId.BARRACKS

    class BarracksFlying(TerranStructure):
        id = UnitTypeId.BARRACKS_FLYING

    class Battlecruiser(Terran):
        id = UnitTypeId.BATTLECRUISER

    class BroodLord(Zerg):
        id = UnitTypeId.BROOD_LORD

    class BroodLordCocoon(Zerg):
        id = UnitTypeId.BROOD_LORD_COCOON

    class Broodling(Zerg):
        id = UnitTypeId.BROODLING

    class Bunker(TerranStructure):
        id = UnitTypeId.BUNKER

    class Carrier(Protoss):
        id = UnitTypeId.CARRIER

    class Changeling(Zerg):
        id = UnitTypeId.CHANGELING

    class ChangelingMarine(Zerg):
        id = UnitTypeId.CHANGELING_MARINE

    class ChangelingMarineShield(Zerg):
        id = UnitTypeId.CHANGELING_MARINE_SHIELD

    class ChangelingZealot(Zerg):
        id = UnitTypeId.CHANGELING_ZEALOT

    class ChangelingZergling(Zerg):
        id = UnitTypeId.CHANGELING_ZERGLING

    class ChangelingZerglingWings(Zerg):
        id = UnitTypeId.CHANGELING_ZERGLING_WINGS

    class CollapsibleTowerDebrisPurifier(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_DEBRIS_PURIFIER

    class CollapsibleTowerDebrisRampLeftRock(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_DEBRIS_RAMP_LEFT_ROCK

    class CollapsibleTowerDebrisRampLeftRockGreen(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_DEBRIS_RAMP_LEFT_ROCK_GREEN

    class CollapsibleTowerDebrisRampRightRock(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_DEBRIS_RAMP_RIGHT_ROCK

    class CollapsibleTowerDebrisRampRightRockGreen(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_DEBRIS_RAMP_RIGHT_ROCK_GREEN

    class CollapsibleTowerDebrisRock(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_DEBRIS_ROCK

    class CollapsibleTowerDebrisTerran(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_DEBRIS_TERRAN

    class CollapsibleTowerDiagonalPurifier(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_DIAGONAL_PURIFIER

    class CollapsibleTowerDiagonalRock(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_DIAGONAL_ROCK

    class CollapsibleTowerDiagonalTerran(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_DIAGONAL_TERRAN

    class CollapsibleTowerPushUnitPurifier(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_PUSH_UNIT_PURIFIER

    class CollapsibleTowerPushUnitRampLeftRock(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_PUSH_UNIT_RAMP_LEFT_ROCK

    class CollapsibleTowerPushUnitRampLeftRockGreen(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_PUSH_UNIT_RAMP_LEFT_ROCK_GREEN

    class CollapsibleTowerPushUnitRampLeftTerran(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_PUSH_UNIT_RAMP_LEFT_TERRAN

    class CollapsibleTowerPushUnitRampRightRock(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_PUSH_UNIT_RAMP_RIGHT_ROCK

    class CollapsibleTowerPushUnitRampRightRockGreen(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_PUSH_UNIT_RAMP_RIGHT_ROCK_GREEN

    class CollapsibleTowerPushUnitRampRightTerran(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_PUSH_UNIT_RAMP_RIGHT_TERRAN

    class CollapsibleTowerPushUnitRock(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_PUSH_UNIT_ROCK

    class CollapsibleTowerPushUnitTerran(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_PUSH_UNIT_TERRAN

    class CollapsibleTowerRampLeftRock(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_RAMP_LEFT_ROCK

    class CollapsibleTowerRampLeftRockGreen(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_RAMP_LEFT_ROCK_GREEN

    class CollapsibleTowerRampLeftTerran(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_RAMP_LEFT_TERRAN

    class CollapsibleTowerRampRightRock(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_RAMP_RIGHT_ROCK

    class CollapsibleTowerRampRightRockGreen(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_RAMP_RIGHT_ROCK_GREEN

    class CollapsibleTowerRampRightTerran(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_RAMP_RIGHT_TERRAN

    class CollapsibleTowerRock(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_ROCK

    class CollapsibleTowerTerran(Structure):
        id = UnitTypeId.COLLAPSIBLE_TOWER_TERRAN

    class Colossus(Protoss):
        id = UnitTypeId.COLOSSUS

    class CommandCenter(TerranStructure):
        id = UnitTypeId.COMMAND_CENTER

    class CommandCenterFlying(TerranStructure):
        id = UnitTypeId.COMMAND_CENTER_FLYING

    class Corruptor(Zerg):
        id = UnitTypeId.CORRUPTOR

    class CreepTumor(ZergStructure):
        id = UnitTypeId.CREEP_TUMOR

    class CreepTumorBurrowed(ZergStructure):
        id = UnitTypeId.CREEP_TUMOR_BURROWED

    class CreepTumorQueen(ZergStructure):
        id = UnitTypeId.CREEP_TUMOR_QUEEN

    class CyberneticsCore(ProtossStructure):
        id = UnitTypeId.CYBERNETICS_CORE

    class Cyclone(Terran):
        id = UnitTypeId.CYCLONE

    class DarkShrine(ProtossStructure):
        id = UnitTypeId.DARK_SHRINE

    class DarkTemplar(Protoss):
        id = UnitTypeId.DARK_TEMPLAR

    class Destructible1x1BraxisAlpha(Structure):
        id = UnitTypeId.DESTRUCTIBLE_1X1_BRAXIS_ALPHA

    class Destructible2x2BraxisAlpha(Structure):
        id = UnitTypeId.DESTRUCTIBLE_2X2_BRAXIS_ALPHA

    class Destructible2x4HorizontalCityDebris(Structure):
        id = UnitTypeId.DESTRUCTIBLE_2X4_HORIZONTAL_CITY_DEBRIS

    class Destructible2x4HorizontalIce(Structure):
        id = UnitTypeId.DESTRUCTIBLE_2X4_HORIZONTAL_ICE

    class Destructible2x4HorizontalRock(Structure):
        id = UnitTypeId.DESTRUCTIBLE_2X4_HORIZONTAL_ROCK

    class Destructible2x4HorizontalRockEx1(Structure):
        id = UnitTypeId.DESTRUCTIBLE_2X4_HORIZONTAL_ROCK_EX1

    class Destructible2x4VerticalCityDebris(Structure):
        id = UnitTypeId.DESTRUCTIBLE_2X4_VERTICAL_CITY_DEBRIS

    class Destructible2x4VerticalIce(Structure):
        id = UnitTypeId.DESTRUCTIBLE_2X4_VERTICAL_ICE

    class Destructible2x4VerticalRock(Structure):
        id = UnitTypeId.DESTRUCTIBLE_2X4_VERTICAL_ROCK

    class Destructible2x4VerticalRockEx1(Structure):
        id = UnitTypeId.DESTRUCTIBLE_2X4_VERTICAL_ROCK_EX1

    class Destructible2x6HorizontalCityDebris(Structure):
        id = UnitTypeId.DESTRUCTIBLE_2X6_HORIZONTAL_CITY_DEBRIS

    class Destructible2x6HorizontalIce(Structure):
        id = UnitTypeId.DESTRUCTIBLE_2X6_HORIZONTAL_ICE

    class Destructible2x6HorizontalRock(Structure):
        id = UnitTypeId.DESTRUCTIBLE_2X6_HORIZONTAL_ROCK

    class Destructible2x6HorizontalRockEx1(Structure):
        id = UnitTypeId.DESTRUCTIBLE_2X6_HORIZONTAL_ROCK_EX1

    class Destructible2x6VerticalCityDebris(Structure):
        id = UnitTypeId.DESTRUCTIBLE_2X6_VERTICAL_CITY_DEBRIS

    class Destructible2x6VerticalIce(Structure):
        id = UnitTypeId.DESTRUCTIBLE_2X6_VERTICAL_ICE

    class Destructible2x6VerticalRock(Structure):
        id = UnitTypeId.DESTRUCTIBLE_2X6_VERTICAL_ROCK

    class Destructible2x6VerticalRockEx1(Structure):
        id = UnitTypeId.DESTRUCTIBLE_2X6_VERTICAL_ROCK_EX1

    class Destructible3x3ZergInfestation(Structure):
        id = UnitTypeId.DESTRUCTIBLE_3X3_ZERG_INFESTATION

    class Destructible4x4CityDebris(Structure):
        id = UnitTypeId.DESTRUCTIBLE_4X4_CITY_DEBRIS

    class Destructible4x4Debris(Structure):
        id = UnitTypeId.DESTRUCTIBLE_4X4_DEBRIS

    class Destructible4x4Ice(Structure):
        id = UnitTypeId.DESTRUCTIBLE_4X4_ICE

    class Destructible4x4Rock(Structure):
        id = UnitTypeId.DESTRUCTIBLE_4X4_ROCK

    class Destructible4x4RockEx1(Structure):
        id = UnitTypeId.DESTRUCTIBLE_4X4_ROCK_EX1

    class Destructible6x6CityDebris(Structure):
        id = UnitTypeId.DESTRUCTIBLE_6X6_CITY_DEBRIS

    class Destructible6x6Debris(Structure):
        id = UnitTypeId.DESTRUCTIBLE_6X6_DEBRIS

    class Destructible6x6ExpeditionGate(Structure):
        id = UnitTypeId.DESTRUCTIBLE_6X6_EXPEDITION_GATE

    class Destructible6x6Ice(Structure):
        id = UnitTypeId.DESTRUCTIBLE_6X6_ICE

    class Destructible6x6Rock(Structure):
        id = UnitTypeId.DESTRUCTIBLE_6X6_ROCK

    class Destructible6x6RockEx1(Structure):
        id = UnitTypeId.DESTRUCTIBLE_6X6_ROCK_EX1

    class Destructible6x6WeakRock(Structure):
        id = UnitTypeId.DESTRUCTIBLE_6X6_WEAK_ROCK

    class DestructibleHugeDiagonalBlurCityDebris(Structure):
        id = UnitTypeId.DESTRUCTIBLE_HUGE_DIAGONAL_BLUR_CITY_DEBRIS

    class DestructibleHugeDiagonalBlurDebrisRamp(Structure):
        id = UnitTypeId.DESTRUCTIBLE_HUGE_DIAGONAL_BLUR_DEBRIS_RAMP

    class DestructibleHugeDiagonalBlurIce(Structure):
        id = UnitTypeId.DESTRUCTIBLE_HUGE_DIAGONAL_BLUR_ICE

    class DestructibleHugeDiagonalBlurRamp(Structure):
        id = UnitTypeId.DESTRUCTIBLE_HUGE_DIAGONAL_BLUR_RAMP

    class DestructibleHugeDiagonalBlurRockEx1(Structure):
        id = UnitTypeId.DESTRUCTIBLE_HUGE_DIAGONAL_BLUR_ROCK_EX1

    class DestructibleHugeDiagonalUlbrCityDebris(Structure):
        id = UnitTypeId.DESTRUCTIBLE_HUGE_DIAGONAL_ULBR_CITY_DEBRIS

    class DestructibleHugeDiagonalUlbrDebrisRamp(Structure):
        id = UnitTypeId.DESTRUCTIBLE_HUGE_DIAGONAL_ULBR_DEBRIS_RAMP

    class DestructibleHugeDiagonalUlbrIce(Structure):
        id = UnitTypeId.DESTRUCTIBLE_HUGE_DIAGONAL_ULBR_ICE

    class DestructibleHugeDiagonalUlbrRamp(Structure):
        id = UnitTypeId.DESTRUCTIBLE_HUGE_DIAGONAL_ULBR_RAMP

    class DestructibleHugeDiagonalUlbrRockEx1(Structure):
        id = UnitTypeId.DESTRUCTIBLE_HUGE_DIAGONAL_ULBR_ROCK_EX1

    class DestructibleHugeHorizontalIce(Structure):
        id = UnitTypeId.DESTRUCTIBLE_HUGE_HORIZONTAL_ICE

    class DestructibleHugeHorizontalRamp(Structure):
        id = UnitTypeId.DESTRUCTIBLE_HUGE_HORIZONTAL_RAMP

    class DestructibleHugeHorizontalRockEx1(Structure):
        id = UnitTypeId.DESTRUCTIBLE_HUGE_HORIZONTAL_ROCK_EX1

    class DestructibleHugeVerticalIce(Structure):
        id = UnitTypeId.DESTRUCTIBLE_HUGE_VERTICAL_ICE

    class DestructibleHugeVerticalRamp(Structure):
        id = UnitTypeId.DESTRUCTIBLE_HUGE_VERTICAL_RAMP

    class DestructibleHugeVerticalRockEx1(Structure):
        id = UnitTypeId.DESTRUCTIBLE_HUGE_VERTICAL_ROCK_EX1

    class DestructibleUnbuildableBricks(Structure):
        id = UnitTypeId.DESTRUCTIBLE_UNBUILDABLE_BRICKS

    class DestructibleUnbuildablePlates(Structure):
        id = UnitTypeId.DESTRUCTIBLE_UNBUILDABLE_PLATES

    class DestructibleUnbuildableRocks(Structure):
        id = UnitTypeId.DESTRUCTIBLE_UNBUILDABLE_ROCKS

    class Disruptor(Protoss):
        id = UnitTypeId.DISRUPTOR

    class Drone(Zerg):
        id = UnitTypeId.DRONE

    class DroneBurrowed(Zerg):
        id = UnitTypeId.DRONE_BURROWED

    class Egg(Zerg):
        id = UnitTypeId.EGG

    class EngineeringBay(TerranStructure):
        id = UnitTypeId.ENGINEERING_BAY

    class EvolutionChamber(ZergStructure):
        id = UnitTypeId.EVOLUTION_CHAMBER

    class Extractor(ZergStructure):
        id = UnitTypeId.EXTRACTOR

    class ExtractorRich(ZergStructure):
        id = UnitTypeId.EXTRACTOR_RICH

    class Factory(TerranStructure):
        id = UnitTypeId.FACTORY

    class FactoryFlying(TerranStructure):
        id = UnitTypeId.FACTORY_FLYING

    class FleetBeacon(ProtossStructure):
        id = UnitTypeId.FLEET_BEACON

    class ForceField(Protoss):
        id = UnitTypeId.FORCE_FIELD

    class Forge(ProtossStructure):
        id = UnitTypeId.FORGE

    class FusionCore(TerranStructure):
        id = UnitTypeId.FUSION_CORE

    class Gateway(ProtossStructure):
        id = UnitTypeId.GATEWAY

    class Ghost(Terran):
        id = UnitTypeId.GHOST

    class GhostAcademy(TerranStructure):
        id = UnitTypeId.GHOST_ACADEMY

    class GreaterSpire(ZergStructure):
        id = UnitTypeId.GREATER_SPIRE

    class Hatchery(ZergStructure):
        id = UnitTypeId.HATCHERY

    class HealingShrineXelNaga(AnyType):
        id = UnitTypeId.HEALING_SHRINE_XEL_NAGA

    class Hellbat(Terran):
        id = UnitTypeId.HELLBAT

    class Hellion(Terran):
        id = UnitTypeId.HELLION

    class HighTemplar(Protoss):
        id = UnitTypeId.HIGH_TEMPLAR

    class Hive(ZergStructure):
        id = UnitTypeId.HIVE

    class Hydralisk(Zerg):
        id = UnitTypeId.HYDRALISK

    class HydraliskBurrowed(Zerg):
        id = UnitTypeId.HYDRALISK_BURROWED

    class HydraliskDen(ZergStructure):
        id = UnitTypeId.HYDRALISK_DEN

    class Immortal(Protoss):
        id = UnitTypeId.IMMORTAL

    class InfestationPit(ZergStructure):
        id = UnitTypeId.INFESTATION_PIT

    class Infestor(Zerg):
        id = UnitTypeId.INFESTOR

    class InfestorBurrowed(Zerg):
        id = UnitTypeId.INFESTOR_BURROWED

    class InhibitorZoneFlyingLarge(Structure):
        id = UnitTypeId.INHIBITOR_ZONE_FLYING_LARGE

    class InhibitorZoneFlyingMedium(Structure):
        id = UnitTypeId.INHIBITOR_ZONE_FLYING_MEDIUM

    class InhibitorZoneFlyingSmall(Structure):
        id = UnitTypeId.INHIBITOR_ZONE_FLYING_SMALL

    class InhibitorZoneLarge(Structure):
        id = UnitTypeId.INHIBITOR_ZONE_LARGE

    class InhibitorZoneMedium(Structure):
        id = UnitTypeId.INHIBITOR_ZONE_MEDIUM

    class InhibitorZoneSmall(Structure):
        id = UnitTypeId.INHIBITOR_ZONE_SMALL

    class Interceptor(Protoss):
        id = UnitTypeId.INTERCEPTOR

    class Lair(ZergStructure):
        id = UnitTypeId.LAIR

    class Larva(Zerg):
        id = UnitTypeId.LARVA

    class Liberator(Terran):
        id = UnitTypeId.LIBERATOR

    class LiberatorSieged(Terran):
        id = UnitTypeId.LIBERATOR_SIEGED

    class Locust(Zerg):
        id = UnitTypeId.LOCUST

    class LocustFlying(Zerg):
        id = UnitTypeId.LOCUST_FLYING

    class Lurker(Zerg):
        id = UnitTypeId.LURKER

    class LurkerBurrowed(Zerg):
        id = UnitTypeId.LURKER_BURROWED

    class LurkerDen(ZergStructure):
        id = UnitTypeId.LURKER_DEN

    class LurkerEgg(Zerg):
        id = UnitTypeId.LURKER_EGG

    class Marauder(Terran):
        id = UnitTypeId.MARAUDER

    class Marine(Terran):
        id = UnitTypeId.MARINE

    class Medivac(Terran):
        id = UnitTypeId.MEDIVAC

    class MineralField(Structure):
        id = UnitTypeId.MINERAL_FIELD

    class MineralField450(Structure):
        id = UnitTypeId.MINERAL_FIELD_450

    class MineralField750(Structure):
        id = UnitTypeId.MINERAL_FIELD_750

    class MineralField750BattleStation(Structure):
        id = UnitTypeId.MINERAL_FIELD_750_BATTLE_STATION

    class MineralField750Lab(Structure):
        id = UnitTypeId.MINERAL_FIELD_750_LAB

    class MineralField750Purifier(Structure):
        id = UnitTypeId.MINERAL_FIELD_750_PURIFIER

    class MineralField900Opaque(Structure):
        id = UnitTypeId.MINERAL_FIELD_900_OPAQUE

    class MineralFieldBattleStation(Structure):
        id = UnitTypeId.MINERAL_FIELD_BATTLE_STATION

    class MineralFieldLab(Structure):
        id = UnitTypeId.MINERAL_FIELD_LAB

    class MineralFieldOpaque(Structure):
        id = UnitTypeId.MINERAL_FIELD_OPAQUE

    class MineralFieldPurifier(Structure):
        id = UnitTypeId.MINERAL_FIELD_PURIFIER

    class MineralFieldRich(Structure):
        id = UnitTypeId.MINERAL_FIELD_RICH

    class MineralFieldRich750(Structure):
        id = UnitTypeId.MINERAL_FIELD_RICH_750

    class MineralFieldRich750Purifier(Structure):
        id = UnitTypeId.MINERAL_FIELD_RICH_750_PURIFIER

    class MineralFieldRichPurifier(Structure):
        id = UnitTypeId.MINERAL_FIELD_RICH_PURIFIER

    class MissileTurret(TerranStructure):
        id = UnitTypeId.MISSILE_TURRET

    class Mothership(Protoss):
        id = UnitTypeId.MOTHERSHIP

    class Mule(Terran):
        id = UnitTypeId.MULE

    class Mutalisk(Zerg):
        id = UnitTypeId.MUTALISK

    class Nexus(ProtossStructure):
        id = UnitTypeId.NEXUS

    class NotAUnit(AnyType):
        id = UnitTypeId.NOT_A_UNIT

    class NydusNetwork(ZergStructure):
        id = UnitTypeId.NYDUS_NETWORK

    class NydusWorm(ZergStructure):
        id = UnitTypeId.NYDUS_WORM

    class Observer(Protoss):
        id = UnitTypeId.OBSERVER

    class ObserverSieged(Protoss):
        id = UnitTypeId.OBSERVER_SIEGED

    class Oracle(Protoss):
        id = UnitTypeId.ORACLE

    class OrbitalCommand(TerranStructure):
        id = UnitTypeId.ORBITAL_COMMAND

    class OrbitalCommandFlying(TerranStructure):
        id = UnitTypeId.ORBITAL_COMMAND_FLYING

    class Overlord(Zerg):
        id = UnitTypeId.OVERLORD

    class OverlordCocoon(Zerg):
        id = UnitTypeId.OVERLORD_COCOON

    class OverlordTransport(Zerg):
        id = UnitTypeId.OVERLORD_TRANSPORT

    class OverlordTransportCocoon(Zerg):
        id = UnitTypeId.OVERLORD_TRANSPORT_COCOON

    class Overseer(Zerg):
        id = UnitTypeId.OVERSEER

    class OverseerSieged(Zerg):
        id = UnitTypeId.OVERSEER_SIEGED

    class Phoenix(Protoss):
        id = UnitTypeId.PHOENIX

    class PhotonCannon(ProtossStructure):
        id = UnitTypeId.PHOTON_CANNON

    class PlanetaryFortress(TerranStructure):
        id = UnitTypeId.PLANETARY_FORTRESS

    class Probe(Protoss):
        id = UnitTypeId.PROBE

    class PurificationNova(Protoss):
        id = UnitTypeId.PURIFICATION_NOVA

    class Pylon(ProtossStructure):
        id = UnitTypeId.PYLON

    class Queen(Zerg):
        id = UnitTypeId.QUEEN

    class QueenBurrowed(Zerg):
        id = UnitTypeId.QUEEN_BURROWED

    class Ravager(Zerg):
        id = UnitTypeId.RAVAGER

    class RavagerBurrowed(Zerg):
        id = UnitTypeId.RAVAGER_BURROWED

    class RavagerCocoon(Zerg):
        id = UnitTypeId.RAVAGER_COCOON

    class Raven(Terran):
        id = UnitTypeId.RAVEN

    class Reactor(TerranStructure):
        id = UnitTypeId.REACTOR

    class ReactorBarracks(TerranStructure):
        id = UnitTypeId.REACTOR_BARRACKS

    class ReactorFactory(TerranStructure):
        id = UnitTypeId.REACTOR_FACTORY

    class ReactorStarport(TerranStructure):
        id = UnitTypeId.REACTOR_STARPORT

    class Reaper(Terran):
        id = UnitTypeId.REAPER

    class ReaperGrenade(TerranStructure):
        id = UnitTypeId.REAPER_GRENADE

    class Refinery(TerranStructure):
        id = UnitTypeId.REFINERY

    class RefineryRich(TerranStructure):
        id = UnitTypeId.REFINERY_RICH

    class Roach(Zerg):
        id = UnitTypeId.ROACH

    class RoachBurrowed(Zerg):
        id = UnitTypeId.ROACH_BURROWED

    class RoachWarren(ZergStructure):
        id = UnitTypeId.ROACH_WARREN

    class RoboticsBay(ProtossStructure):
        id = UnitTypeId.ROBOTICS_BAY

    class RoboticsFacility(ProtossStructure):
        id = UnitTypeId.ROBOTICS_FACILITY

    class Rocks2x2NonConjoined(Structure):
        id = UnitTypeId.ROCKS_2X2_NON_CONJOINED

    class Scv(Terran):
        id = UnitTypeId.SCV

    class SensorTower(TerranStructure):
        id = UnitTypeId.SENSOR_TOWER

    class Sentry(Protoss):
        id = UnitTypeId.SENTRY

    class ShieldBattery(ProtossStructure):
        id = UnitTypeId.SHIELD_BATTERY

    class SiegeTank(Terran):
        id = UnitTypeId.SIEGE_TANK

    class SiegeTankSieged(Terran):
        id = UnitTypeId.SIEGE_TANK_SIEGED

    class SpawningPool(ZergStructure):
        id = UnitTypeId.SPAWNING_POOL

    class SpineCrawler(ZergStructure):
        id = UnitTypeId.SPINE_CRAWLER

    class SpineCrawlerUprooted(ZergStructure):
        id = UnitTypeId.SPINE_CRAWLER_UPROOTED

    class Spire(ZergStructure):
        id = UnitTypeId.SPIRE

    class SporeCrawler(ZergStructure):
        id = UnitTypeId.SPORE_CRAWLER

    class SporeCrawlerUprooted(ZergStructure):
        id = UnitTypeId.SPORE_CRAWLER_UPROOTED

    class Stalker(Protoss):
        id = UnitTypeId.STALKER

    class Stargate(ProtossStructure):
        id = UnitTypeId.STARGATE

    class Starport(TerranStructure):
        id = UnitTypeId.STARPORT

    class StarportFlying(TerranStructure):
        id = UnitTypeId.STARPORT_FLYING

    class StasisWard(ProtossStructure):
        id = UnitTypeId.STASIS_WARD

    class SupplyDepot(TerranStructure):
        id = UnitTypeId.SUPPLY_DEPOT

    class SupplyDepotLowered(TerranStructure):
        id = UnitTypeId.SUPPLY_DEPOT_LOWERED

    class SwarmHost(Zerg):
        id = UnitTypeId.SWARM_HOST

    class SwarmHostBurrowed(Zerg):
        id = UnitTypeId.SWARM_HOST_BURROWED

    class TechLab(TerranStructure):
        id = UnitTypeId.TECH_LAB

    class TechLabBarracks(TerranStructure):
        id = UnitTypeId.TECH_LAB_BARRACKS

    class TechLabFactory(TerranStructure):
        id = UnitTypeId.TECH_LAB_FACTORY

    class TechLabStarport(TerranStructure):
        id = UnitTypeId.TECH_LAB_STARPORT

    class Tempest(Protoss):
        id = UnitTypeId.TEMPEST

    class TemplarArchive(ProtossStructure):
        id = UnitTypeId.TEMPLAR_ARCHIVE

    class Thor(Terran):
        id = UnitTypeId.THOR

    class ThorHighImpact(Terran):
        id = UnitTypeId.THOR_HIGH_IMPACT

    class TwilightCouncil(ProtossStructure):
        id = UnitTypeId.TWILIGHT_COUNCIL

    class Ultralisk(Zerg):
        id = UnitTypeId.ULTRALISK

    class UltraliskBurrowed(Zerg):
        id = UnitTypeId.ULTRALISK_BURROWED

    class UltraliskCavern(ZergStructure):
        id = UnitTypeId.ULTRALISK_CAVERN

    class VespeneGeyser(Structure):
        id = UnitTypeId.VESPENE_GEYSER

    class VespeneGeyserProtoss(Structure):
        id = UnitTypeId.VESPENE_GEYSER_PROTOSS

    class VespeneGeyserPurifier(Structure):
        id = UnitTypeId.VESPENE_GEYSER_PURIFIER

    class VespeneGeyserRich(Structure):
        id = UnitTypeId.VESPENE_GEYSER_RICH

    class VespeneGeyserShakuras(Structure):
        id = UnitTypeId.VESPENE_GEYSER_SHAKURAS

    class VespeneGeyserSpacePlatform(Structure):
        id = UnitTypeId.VESPENE_GEYSER_SPACE_PLATFORM

    class Viking(Terran):
        id = UnitTypeId.VIKING

    class VikingLanded(Terran):
        id = UnitTypeId.VIKING_LANDED

    class Viper(Zerg):
        id = UnitTypeId.VIPER

    class VoidRay(Protoss):
        id = UnitTypeId.VOID_RAY

    class WarpGate(ProtossStructure):
        id = UnitTypeId.WARP_GATE

    class WarpPrism(Protoss):
        id = UnitTypeId.WARP_PRISM

    class WarpPrismPhasing(Protoss):
        id = UnitTypeId.WARP_PRISM_PHASING

    class Watchtower(Structure):
        id = UnitTypeId.WATCHTOWER

    class WidowMine(Terran):
        id = UnitTypeId.WIDOW_MINE

    class WidowMineBurrowed(Terran):
        id = UnitTypeId.WIDOW_MINE_BURROWED

    class Zealot(Protoss):
        id = UnitTypeId.ZEALOT

    class Zergling(Zerg):
        id = UnitTypeId.ZERGLING

    class ZerglingBurrowed(Zerg):
        id = UnitTypeId.ZERGLING_BURROWED
