"""Generate the raw identifier catalogs from `data/stableid.json`.

The raw enums are the *complete* catalog: every entry Blizzard ships, named as closely to Blizzard's own name as a
Python identifier allows. They are not the public API — the curated enums in `sc2nachos/ids/` are, and each curated
member is defined from a raw member so that no game id is ever written as a bare integer.

Regenerate after a patch changes stableid.json::

    uv run python tools/generate_ids.py

`data/stableid.json` is vendored, so this runs without StarCraft II. The game rewrites the file from whichever map it
last loaded, so refresh it from a current ladder map, as `docs/curating-ids.md` says.
"""

import json
import keyword
import re
from collections import Counter
from pathlib import Path

REPO = Path(__file__).parents[1]
STABLE_ID = REPO / "data" / "stableid.json"
OUTPUT_DIR = REPO / "src" / "sc2nachos" / "ids" / "raw"

# category -> (module name, enum name, what one member is)
CATEGORIES = {
    "Units": ("unit_type", "RawUnitTypeId", "unit"),
    "Abilities": ("ability", "RawAbilityId", "ability"),
    "Upgrades": ("upgrade", "RawUpgradeId", "upgrade"),
    "Buffs": ("buff", "RawBuffId", "buff"),
    "Effects": ("effect", "RawEffectId", "effect"),
}

HEADER = '''"""Raw {category} identifiers — the complete catalog from Blizzard's stableid.json.

DO NOT EDIT. Generated by `tools/generate_ids.py`. Curate names in `sc2nachos/ids/{module}.py` instead.
"""

from sc2nachos._enum import ReadableIntEnum


class {enum}(ReadableIntEnum):
    """Every {singular} id the game defines, named as Blizzard names it."""

'''


def make_identifier(name: str) -> str:
    """Turn a Blizzard name into a valid Python identifier, changing it as little as possible."""
    identifier = re.sub(r"[^0-9a-zA-Z_]", "", name.replace(" ", "_"))
    if not identifier:
        return ""
    if identifier[0].isdigit():
        identifier = f"_{identifier}"
    if keyword.iskeyword(identifier):
        identifier = f"{identifier}_"
    return identifier


def ability_name(entry: dict) -> str:
    """The identifier for an ability.

    `name` is not unique — 894 repeat, since one name such as `TerranBuild` covers every structure it can build.
    Blizzard's own disambiguator is `buttonname`, so the pair identifies an ability; `friendlyname` is preferred where
    the game supplies one.
    """
    name, button = entry.get("name", ""), entry.get("buttonname", "")
    friendly = entry.get("friendlyname", "")
    if friendly:
        return make_identifier(friendly)
    if name and button:
        return make_identifier(f"{name}_{button}")
    return make_identifier(name or button)


def collect(category: str, entries: list[dict]) -> dict[str, int]:
    """Map identifier -> id for one category, dropping unnamed entries and resolving collisions."""
    named: list[tuple[str, int]] = []
    for entry in entries:
        name = ability_name(entry) if category == "Abilities" else make_identifier(entry.get("name", ""))
        if name:
            named.append((name, entry["id"]))

    # On a collision the lowest id keeps the bare name and the rest get an id suffix, so every entry stays reachable
    # and the common member keeps the obvious name.
    counts = Counter(name for name, _ in named)
    seen: set[str] = set()
    members: dict[str, int] = {}
    for name, id_ in sorted(named, key=lambda pair: pair[1]):
        key = name if counts[name] == 1 or name not in seen else f"{name}_{id_}"
        seen.add(name)
        members[key] = id_
    return members


def render() -> dict[Path, str]:
    """The text of every module the generator writes, by path."""
    data = json.loads(STABLE_ID.read_text(encoding="utf-8"))
    modules: dict[Path, str] = {}
    for category, (module, enum, singular) in CATEGORIES.items():
        members = collect(category, data[category])
        lines = [HEADER.format(category=category, singular=singular, module=module, enum=enum)]
        lines += [f"    {name} = {id_}\n" for name, id_ in members.items()]
        modules[OUTPUT_DIR / f"{module}.py"] = "".join(lines)

    # Sorted so the generated file passes the import linter as written.
    enums = sorted((module, enum) for module, enum, _ in CATEGORIES.values())
    exports = "\n".join(f"from sc2nachos.ids.raw.{module} import {enum}" for module, enum in enums)
    names = "\n".join(f'    "{enum}",' for _, enum in enums)
    modules[OUTPUT_DIR / "__init__.py"] = (
        f'"""Raw identifier catalogs, generated from stableid.json."""\n\n{exports}\n\n__all__ = [\n{names}\n]\n'
    )
    return modules


def generate() -> None:
    """Write one module per category, and the package that exports them."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, text in render().items():
        path.write_text(text, encoding="utf-8")
        print(f"{path.name}: {text.count(chr(10))} lines")


if __name__ == "__main__":
    generate()
