"""Generate `sc2nachos/units/_unit_type.py`: `UnitType`, with a class for every curated unit type and every group.

A type is in the group of its race, and in `Structure` where the game's tables give it the structure attribute. Both
come from the tables of a corpus game, so this runs without StarCraft II. Run it again after changing `UnitTypeId`::

    uv run python tools/generate_unit_types.py
"""

from pathlib import Path

from sc2nachos.gamedata import Attribute, GameData
from sc2nachos.ids import UnitTypeId
from sc2nachos.match import Race
from sc2nachos.protocol import Recording

REPO = Path(__file__).parents[1]
CORPUS = REPO / "tests" / "corpus"
OUTPUT = REPO / "src" / "sc2nachos" / "units" / "_unit_type.py"

HEADER = '''"""Every type of unit, and the groups the game's tables put them in, as classes for the type checker.

DO NOT EDIT. Generated by `tools/generate_unit_types.py`; run it again after changing `UnitTypeId`.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, ClassVar, Self, TypeGuard, cast, overload

from sc2nachos.ids import UnitTypeId

if TYPE_CHECKING:
    from sc2nachos.units._own_unit import OwnUnit
    from sc2nachos.units._unit import Unit


class UnitType:
    """Every type of unit, and every group of types, for the type checker. None is ever instantiated.

    `Unit[UnitType.Marine]` is a marine, and `Unit[UnitType.ProtossStructure]` a Protoss structure. A type's `id` is
    its `UnitTypeId`. A group is a race, the structures, or the structures of a race, as the game's tables give them.
    """

    class AnyType:
        """Any type of unit, and what every type and group is.

        `type[UnitType.AnyType]` takes any of them. `Unit[Any]` is a unit that reads as any type, where
        `Unit[UnitType.AnyType]` is one whose type the type checker does not know, so a read only some types have is an
        error on it until `includes` narrows it.
        """

        _type_ids: ClassVar[frozenset[UnitTypeId]] = frozenset()

        def __init_subclass__(cls) -> None:
            """Add the type a class names by its `id` to every group it is in. A class without an `id` is a group."""
            super().__init_subclass__()
            type_id: UnitTypeId | None = cls.__dict__.get("id")
            cls._type_ids = frozenset() if type_id is None else frozenset((type_id,))
            if type_id is not None:
                # Everything between the class and `object` is a group it is in, `AnyType` included.
                for group in cast("tuple[type[UnitType.AnyType], ...]", cls.__mro__[1:-1]):
                    group._type_ids |= cls._type_ids

        @overload
        @classmethod
        def includes(cls, unit: OwnUnit[Any], /) -> TypeGuard[OwnUnit[Self]]: ...

        @overload
        @classmethod
        def includes(cls, unit: Unit[Any], /) -> TypeGuard[Unit[Self]]: ...

        @classmethod
        def includes(cls, unit: Unit[Any], /) -> bool:
            """Whether `unit` is of this type, or of a type in this group, narrowing it for the type checker.

            Raises `UncuratedIdError` for a unit of a type the curated ids leave out.
            """
            return unit.type_id in cls._type_ids
'''

# The races with a group of their own. A map's own units, such as mineral fields and rocks, have no race.
RACES = {Race.TERRAN: "Terran", Race.ZERG: "Zerg", Race.PROTOSS: "Protoss"}


def class_name(unit_type: UnitTypeId) -> str:
    """The class name of a type: `SIEGE_TANK_SIEGED` is `SiegeTankSieged`."""
    return "".join(part.capitalize() for part in unit_type.name.split("_"))


def render(tables: GameData) -> str:
    """The module, for the types in `tables`."""
    groups = {
        "Structure": ("AnyType", "A type the game's tables give the structure attribute."),
        **{name: ("AnyType", f"A {name} type.") for name in RACES.values()},
        **{f"{name}Structure": (f"{name}, Structure", f"A {name} structure.") for name in RACES.values()},
    }
    blocks = [HEADER]
    for name, (bases, docstring) in groups.items():
        blocks.append(f'    class {name}({bases}):\n        """{docstring}"""\n')
    names = set(groups)
    for unit_type in sorted(UnitTypeId, key=class_name):
        row = tables.units[unit_type]
        name = class_name(unit_type)
        if name in names:
            raise ValueError(f"{unit_type!r} would be named {name}, which is already taken")
        names.add(name)
        race = RACES.get(row.race)
        structure = Attribute.STRUCTURE in row.attributes
        base = f"{race}Structure" if race and structure else race or ("Structure" if structure else "AnyType")
        blocks.append(f"    class {name}({base}):\n        id = UnitTypeId.{unit_type.name}\n")
    return "\n".join(blocks)


def corpus_tables() -> GameData:
    """The tables of the first corpus game, which every game on the current ladder shares."""
    recording = Recording(sorted(CORPUS.glob("*.sc2rec"))[0])
    return GameData(next(exchange.response.data for exchange in recording if exchange.response.HasField("data")))


if __name__ == "__main__":
    OUTPUT.write_text(render(corpus_tables()), encoding="utf-8")
    print(f"{OUTPUT.name}: {len(UnitTypeId)} types")
