"""Generate `sc2nachos/gamedata/_tech_tree_<build>.py` from `data/tech_tree.json`, which `tools/sweep_tech_tree.py`
writes.

Keeps what the curated ids name, and runs without StarCraft II. Run it again after sweeping, or after changing the
curated ids::

    uv run python tools/generate_tech_tree.py

A sweep on a new build writes a new module beside the old one, and `gamedata/_gamedata.py` imports the one it plays by.
"""

import json
from collections import defaultdict
from collections.abc import Callable, Iterable, Mapping
from dataclasses import fields, is_dataclass
from enum import IntEnum
from pathlib import Path
from types import MappingProxyType

from sc2nachos.gamedata import TechRequirements
from sc2nachos.gamedata._overrides import CREATION_ABILITY_OVERRIDES
from sc2nachos.gamedata._tech_tree import TechTree
from sc2nachos.ids import AbilityId, UnitTypeId, UpgradeId
from sc2nachos.ids.raw import RawAbilityId, RawUnitTypeId, RawUpgradeId

REPO = Path(__file__).parents[1]
INPUT = REPO / "data" / "tech_tree.json"
GAMEDATA = REPO / "src" / "sc2nachos" / "gamedata"

HEADER = '''"""The tech tree of build {base_build}, as `tools/sweep_tech_tree.py` found it in game.

DO NOT EDIT. Generated by `tools/generate_tech_tree.py` from `data/tech_tree.json`.
"""

from types import MappingProxyType
from typing import Final

from sc2nachos.gamedata._tech_requirements import TechRequirements
from sc2nachos.gamedata._tech_tree import TechTree
from sc2nachos.ids import AbilityId, UnitTypeId, UpgradeId

'''

type Trial = tuple[UnitTypeId, AbilityId, UnitTypeId, str]
"""A unit type ordered an ability, the unit type the ability makes, and what the order did."""


def read(findings: Mapping[str, object]) -> TechTree:
    """What `findings`, as the sweep writes them, say about what the curated ids name.

    A unit type offered an ability that makes something, which then turned it into something else, is taken as not
    offered it: once Burrow is researched, a zergling is offered every zerg unit's burrow, and burrows as a zergling
    whichever it is ordered.

    Raises `ValueError` where a requirement is something no curated id names, where an add-on required was not seen
    to count only on the unit's own structure, where a unit type is offered an ability whose requirements were never
    read, which would otherwise read as needing nothing, or where the sweep did not see an override in
    `gamedata/_overrides.py` make its unit type.
    """
    trials = _trials(findings)
    made = {(ability, product) for _, ability, product, result in trials if result in ("morph", "build")}
    if unconfirmed := sorted(
        f"{u.name} by {a.name}" for u, a in CREATION_ABILITY_OVERRIDES.items() if (a, u) not in made
    ):
        raise ValueError(f"the sweep did not see these overrides make their unit type: {', '.join(unconfirmed)}")

    turned = {(performer, ability) for performer, ability, _, result in trials if result == "other"}
    offered: dict[UnitTypeId, set[AbilityId]] = {}
    for type_name, ability_names in _mapping(findings["offered"]).items():
        if (unit_type := _unit_type(type_name)) is not None:
            abilities = filter(None, map(_ability, _strings(ability_names)))
            offered[unit_type] = {ability for ability in abilities if (unit_type, ability) not in turned}

    needs: dict[tuple[UnitTypeId, AbilityId], TechRequirements] = {}
    for record in _records(findings["requirements"]):
        performer, ability = _unit_type(str(record["performer"])), _ability(str(record["ability"]))
        if performer is None or ability is None or ability not in offered.get(performer, ()):
            continue
        structures = frozenset(_required(_unit_type, record["structures"]))
        if any(_is_add_on(structure) for structure in structures) and not record["attached"]:
            raise ValueError(f"{performer.name} is offered {ability.name} with another structure's add-on")
        needs[performer, ability] = TechRequirements(structures, frozenset(_required(_upgrade, record["upgrades"])))
    pairs = [(unit, ability) for unit, abilities in offered.items() for ability in abilities]
    if unread := sorted(f"{unit.name} {ability.name}" for unit, ability in pairs if (unit, ability) not in needs):
        raise ValueError(f"what these need was never read: {', '.join(unread)}")

    creation_abilities = _creation_abilities(findings)
    return TechTree(
        base_build=int(str(findings["base_build"])),
        ability_requirements=MappingProxyType(
            {
                unit: MappingProxyType({ability: needs[unit, ability] for ability in abilities})
                for unit, abilities in offered.items()
            }
        ),
        ability_remaps=MappingProxyType(_remaps(findings)),
        creation_abilities=MappingProxyType(creation_abilities),
        ability_products=MappingProxyType(_products(creation_abilities, findings)),
        morph_sources=MappingProxyType(_morph_sources(trials)),
        # A pylon reads as powered, by itself.
        power_consumers=frozenset(filter(None, map(_unit_type, _strings(findings["powered"])))) - {UnitTypeId.PYLON},
    )


def uncurated(findings: Mapping[str, object]) -> frozenset[str]:
    """What the curated unit types are offered that no curated ability names, in the raw catalog's spelling."""
    offered = _mapping(findings["offered"]).items()
    names = (name for type_name, abilities in offered if _unit_type(type_name) for name in _strings(abilities))
    return frozenset(name for name in names if _ability(name) is None)


def _remaps(findings: Mapping[str, object]) -> dict[AbilityId, AbilityId]:
    """The general ability each ability stands for, as the game's table says, where the curated ids name both."""
    remaps = _mapping(findings["remaps"]).items()
    return {exact: general for e, g in remaps if (exact := _ability(e)) and (general := _ability(str(g)))}


def _creation_abilities(findings: Mapping[str, object]) -> dict[UnitTypeId, AbilityId]:
    """The ability that makes each unit type: what the game's table names where that works, and the override where
    it does not."""
    named = {
        unit_type: ability
        for type_name, ability_name in _mapping(findings["creation_abilities"]).items()
        if (unit_type := _unit_type(type_name)) and (ability := _ability(str(ability_name)))
    }
    return named | {
        unit_type: ability for unit_type, ability in CREATION_ABILITY_OVERRIDES.items() if unit_type not in named
    }


def _products(
    creation_abilities: Mapping[UnitTypeId, AbilityId], findings: Mapping[str, object]
) -> dict[AbilityId, UnitTypeId | UpgradeId]:
    """The unit type or upgrade each ability makes. An override sharing its ability with a type the game's table names
    it for, as a rich refinery shares the plain build with a refinery, leaves the table's product standing."""
    products: dict[AbilityId, UnitTypeId | UpgradeId] = {}
    for unit_type, ability in sorted(
        creation_abilities.items(), key=lambda entry: entry[0] in CREATION_ABILITY_OVERRIDES
    ):
        products.setdefault(ability, unit_type)
    for upgrade_name, ability_name in _mapping(findings["research_abilities"]).items():
        if (upgrade := _upgrade(upgrade_name)) and (ability := _ability(str(ability_name))):
            products[ability] = upgrade
    return products


def _morph_sources(trials: Iterable[Trial]) -> dict[UnitTypeId, UnitTypeId]:
    """The type each unit type is made out of, from the trials that used the unit ordered up.

    Where several types can be used up making one, it is the one the others are themselves made out of: an overseer is
    made out of an overlord, and out of the overlord transport an overlord becomes.
    """
    used_up: defaultdict[UnitTypeId, set[UnitTypeId]] = defaultdict(set)
    for performer, _, product, result in trials:
        if result == "morph":
            used_up[product].add(performer)
    sources: dict[UnitTypeId, UnitTypeId] = {}
    for product, performers in used_up.items():
        roots = [performer for performer in performers if not used_up.get(performer, set()) & performers]
        if len(roots) == 1:
            sources[product] = roots[0]
    return sources


def render(tech_tree: TechTree) -> str:
    """The module holding `tech_tree`."""
    return HEADER.format(base_build=tech_tree.base_build) + f"TECH_TREE: Final = {_literal(tech_tree, 0)}\n"


def output(tech_tree: TechTree) -> Path:
    """Where the module holding `tech_tree` goes."""
    return GAMEDATA / f"_tech_tree_{tech_tree.base_build}.py"


def _literal(value: object, indent: int) -> str:
    """`value` as a Python expression starting at column `indent`: one member a line, each bracket beside the
    parenthesis it opens in, and what the tech tree holds for one ability on one line. `pyproject.toml` keeps the module
    out of ruff's formatter and its line length, which would undo both."""
    pad, inner = " " * indent, " " * (indent + 4)
    if isinstance(value, IntEnum):
        return f"{type(value).__name__}.{value.name}"
    if isinstance(value, bool | int):
        return repr(value)
    if isinstance(value, frozenset):
        if not value:
            return "frozenset()"
        members = "".join(f"{inner}{_literal(member, indent + 4)},\n" for member in sorted(value, key=_order))
        return f"frozenset({{\n{members}{pad}}})"
    if isinstance(value, Mapping):
        if not value:
            return "MappingProxyType({})"
        entries = sorted(value.items(), key=lambda entry: _order(entry[0]))
        lines = "".join(f"{inner}{_literal(k, indent + 4)}: {_literal(v, indent + 4)},\n" for k, v in entries)
        return f"MappingProxyType({{\n{lines}{pad}}})"
    if is_dataclass(value) and not isinstance(value, type):
        # What a class works out for itself is not given to it, and a default is left to it.
        given = [(field.name, getattr(value, field.name)) for field in fields(value) if field.init]
        given = [(name, member) for name, member in given if member != _default(value, name)]
        if indent:
            return f"{type(value).__name__}({', '.join(f'{name}={_inline(member)}' for name, member in given)})"
        lines = "".join(f"{inner}{name}={_literal(member, indent + 4)},\n" for name, member in given)
        return f"{type(value).__name__}(\n{lines}{pad})"
    raise TypeError(f"no literal for {value!r}")


def _inline(value: object) -> str:
    """`value` as a Python expression on one line."""
    if isinstance(value, IntEnum):
        return f"{type(value).__name__}.{value.name}"
    if isinstance(value, frozenset):
        return (
            f"frozenset({{{', '.join(_inline(member) for member in sorted(value, key=_order))}}})"
            if value
            else "frozenset()"
        )
    raise TypeError(f"no literal for {value!r}")


def _default(value: object, name: str) -> object:
    """The default of the field `name` of the dataclass `value`, which no value equals where there is none."""
    return next(field.default for field in fields(value) if field.name == name)  # type: ignore[arg-type]


def _is_add_on(unit_type: UnitTypeId) -> bool:
    return "TECH_LAB" in unit_type.name or "REACTOR" in unit_type.name


def _order(value: object) -> str:
    return value.name if isinstance(value, IntEnum) else str(value)


def _trials(findings: Mapping[str, object]) -> list[Trial]:
    trials: list[Trial] = []
    for record in _records(findings["made"]):
        performer, ability = _unit_type(str(record["performer"])), _ability(str(record["ability"]))
        product = _unit_type(str(record["product"]))
        if performer is not None and ability is not None and product is not None:
            trials.append((performer, ability, product, str(record["result"])))
    return trials


def _unit_type(name: str) -> UnitTypeId | None:
    return UnitTypeId.get(RawUnitTypeId[name]) if name in RawUnitTypeId.__members__ else None


def _ability(name: str) -> AbilityId | None:
    return AbilityId.get(RawAbilityId[name]) if name in RawAbilityId.__members__ else None


def _upgrade(name: str) -> UpgradeId | None:
    return UpgradeId.get(RawUpgradeId[name]) if name in RawUpgradeId.__members__ else None


def _required[IdT](lookup: Callable[[str], IdT | None], names: object) -> Iterable[IdT]:
    """Each name curated, raising where one is not."""
    for name in _strings(names):
        if (member := lookup(name)) is None:
            raise ValueError(f"{name} is required, and no curated id names it")
        yield member


def _mapping(value: object) -> dict[str, object]:
    assert isinstance(value, dict)
    return {str(key): item for key, item in value.items()}


def _strings(value: object) -> list[str]:
    assert isinstance(value, list)
    return [str(item) for item in value]


def _records(value: object) -> list[dict[str, object]]:
    assert isinstance(value, list)
    return [_mapping(item) for item in value]


if __name__ == "__main__":
    findings = json.loads(INPUT.read_text(encoding="utf-8"))
    tech_tree = read(findings)
    module = output(tech_tree)
    module.write_text(render(tech_tree), encoding="utf-8")
    print(f"{module.name}: {len(tech_tree.ability_requirements)} unit types, {len(tech_tree.morph_sources)} morphs")
    if f"from sc2nachos.gamedata.{module.stem} import" not in (GAMEDATA / "_gamedata.py").read_text(encoding="utf-8"):
        print(f"gamedata/_gamedata.py does not import {module.stem} yet")
    print(f"{len(uncurated(findings))} abilities are offered that no curated id names")
