"""Generate the raw identifier catalogs from `data/stableid.json`.

The raw enums are the *complete* catalog: every entry Blizzard ships, named as closely to Blizzard's own name as a
Python identifier allows. They are not the user-facing API — the curated enums in `sc2nachos/ids/` are, and each of
their members is defined in terms of a raw member so that no game id is ever written out as a bare integer.

Regenerate after a patch changes stableid.json::

    uv run python tools/generate_ids.py

Vendoring stableid.json means this runs without StarCraft II installed. The game rewrites the file from whichever
map it last loaded, so refresh it from a current ladder map, as `docs/curating-ids.md` says.
"""

import json
import keyword
import re
from collections import Counter
from pathlib import Path

REPO = Path(__file__).parents[1]
STABLE_ID = REPO / "data" / "stableid.json"
OUTPUT_DIR = REPO / "src" / "sc2nachos" / "ids" / "raw"

# category -> (module name, enum name)
CATEGORIES = {
    "Units": ("unit_type", "RawUnitTypeId"),
    "Abilities": ("ability", "RawAbilityId"),
    "Upgrades": ("upgrade", "RawUpgradeId"),
    "Buffs": ("buff", "RawBuffId"),
    "Effects": ("effect", "RawEffectId"),
}

HEADER = '''"""Raw {category} identifiers — the complete catalog from Blizzard's stableid.json.

DO NOT EDIT. Generated by `tools/generate_ids.py`. Curate names in `sc2nachos/ids/{module}.py` instead.
"""

from sc2nachos.ids._base import ReadableIntEnum


class {enum}(ReadableIntEnum):
    """Every {category_lower} id the game defines, named as Blizzard names it."""

'''


def make_identifier(name: str) -> str:
    """Turn a Blizzard name into a valid Python identifier, changing it as little as possible."""
    identifier = re.sub(r"[^0-9a-zA-Z_]", "", name.replace(" ", "_"))
    if not identifier:
        return ""
    if identifier[0].isdigit():
        identifier = f"_{identifier}"
    if keyword.iskeyword(identifier):
        identifier = f"{identifier}_"
    return identifier


def ability_name(entry: dict) -> str:
    """Derive a name for an ability.

    Ability `name` is not unique — 894 of them repeat, because one name such as `TerranBuild` covers every
    building it can produce. Blizzard's own disambiguator is `buttonname`, so the pair is what identifies an
    ability, with `friendlyname` preferred when the game supplies one.
    """
    name, button = entry.get("name", ""), entry.get("buttonname", "")
    friendly = entry.get("friendlyname", "")
    if friendly:
        return make_identifier(friendly)
    if name and button:
        return make_identifier(f"{name}_{button}")
    return make_identifier(name or button)


def collect(category: str, entries: list[dict]) -> dict[str, int]:
    """Map identifier -> id for one category, dropping unnamed entries and resolving collisions."""
    named: list[tuple[str, int]] = []
    for entry in entries:
        name = ability_name(entry) if category == "Abilities" else make_identifier(entry.get("name", ""))
        if name:
            named.append((name, entry["id"]))

    # A residual collision keeps the lowest id under the bare name and suffixes the rest, so every catalog entry
    # stays reachable and the common member keeps the obvious name.
    counts = Counter(name for name, _ in named)
    seen: set[str] = set()
    members: dict[str, int] = {}
    for name, id_ in sorted(named, key=lambda pair: pair[1]):
        key = name if counts[name] == 1 or name not in seen else f"{name}_{id_}"
        seen.add(name)
        members[key] = id_
    return members


def generate() -> None:
    """Write one module per category."""
    data = json.loads(STABLE_ID.read_text(encoding="utf-8"))
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for category, (module, enum) in CATEGORIES.items():
        members = collect(category, data[category])
        lines = [
            HEADER.format(category=category, category_lower=category.lower().rstrip("s"), module=module, enum=enum)
        ]
        lines += [f"    {name} = {id_}\n" for name, id_ in members.items()]
        (OUTPUT_DIR / f"{module}.py").write_text("".join(lines), encoding="utf-8")
        print(f"{module}.py: {len(members)} members")

    # Sorted so the generated file satisfies the import linter without a post-pass.
    modules = sorted(CATEGORIES.values())
    exports = "\n".join(f"from sc2nachos.ids.raw.{module} import {enum}" for module, enum in modules)
    names = "\n".join(f'    "{enum}",' for _, enum in modules)
    (OUTPUT_DIR / "__init__.py").write_text(
        f'"""Raw identifier catalogs, generated from stableid.json."""\n\n{exports}\n\n__all__ = [\n{names}\n]\n',
        encoding="utf-8",
    )


if __name__ == "__main__":
    generate()
