"""Generate `sc2nachos/gamedata/_techtree/_build_<build>.py` from `data/tech_tree.json` and `data/upgrades.json`, which
`tools/sweep_tech_tree.py` and `tools/sweep_upgrades.py` write.

Keeps what the curated ids name, and runs without StarCraft II. Run it again after sweeping, or after changing the
curated ids::

    uv run python tools/generate_tech_tree.py

A sweep on a new build writes a new module beside the old one, and `gamedata/_techtree/__init__.py` imports the one
NachOS plays by.
"""

import json
from collections import defaultdict
from collections.abc import Callable, Iterable, Mapping
from dataclasses import MISSING, dataclass, fields, is_dataclass
from enum import IntEnum
from pathlib import Path
from types import MappingProxyType

from sc2nachos.constants import FASTER_PER_NORMAL_SPEED
from sc2nachos.gamedata import Attribute, TechRequirements, UnitTypeUpgrade, UpgradeType, WeaponUpgrade
from sc2nachos.gamedata._techtree import MISNAMED_RESEARCH_ABILITIES, UNNAMED_CREATION_ABILITIES, TechTree
from sc2nachos.ids import AbilityId, UnitTypeId, UpgradeId
from sc2nachos.ids.raw import RawAbilityId, RawUnitTypeId, RawUpgradeId

REPO = Path(__file__).parents[1]
INPUT = REPO / "data" / "tech_tree.json"
UPGRADE_INPUT = REPO / "data" / "upgrades.json"
TECHTREE = REPO / "src" / "sc2nachos" / "gamedata" / "_techtree"

HEADER = '''"""The tech tree of build {base_build}, as the sweeps in `tools` found it in game.

DO NOT EDIT. Generated by `tools/generate_tech_tree.py` from `data/tech_tree.json` and `data/upgrades.json`.
"""

from types import MappingProxyType
from typing import Final

from sc2nachos.gamedata._tech_requirements import TechRequirements
from sc2nachos.gamedata._techtree._tech_tree import TechTree
from sc2nachos.gamedata._unit_type_upgrade import UnitTypeUpgrade, WeaponUpgrade
from sc2nachos.gamedata._unittype import Attribute
from sc2nachos.gamedata._upgrade import UpgradeType
from sc2nachos.ids import AbilityId, UnitTypeId, UpgradeId

'''

type Trial = tuple[UnitTypeId, AbilityId, UnitTypeId, str]
"""A unit type ordered an ability, the unit type the ability makes, and what the order did."""


def read(findings: Mapping[str, object], upgrade_findings: Mapping[str, object]) -> TechTree:
    """What `findings` and `upgrade_findings`, as the sweeps write them, say about what the curated ids name.

    A unit type offered an ability that makes something, which then turned it into something else, is taken as not
    offered it: once Burrow is researched, a zergling is offered every zerg unit's burrow, and burrows as a zergling
    whichever it is ordered.

    Raises `ValueError` where a requirement is something no curated id names, where an add-on required was not seen
    to count only on the unit's own structure, where a unit type is offered an ability whose requirements were never
    read, which would otherwise read as needing nothing, or where the sweep did not see an ability in
    `gamedata/_techtree/_overrides.py` make its unit type, or where that file lists more than one ability for a type the
    table names no working ability for. Raises it too for what `read_upgrades` raises for, and where the two sweeps
    played different builds.
    """
    if findings["base_build"] != upgrade_findings["base_build"]:
        raise ValueError(
            f"the tech tree was swept on build {findings['base_build']} and the upgrades on "
            f"{upgrade_findings['base_build']}"
        )
    found = read_upgrades(upgrade_findings)
    trials = _trials(findings)
    made = {(ability, product) for _, ability, product, result in trials if result in ("morph", "build")}
    if unconfirmed := sorted(
        f"{u.name} by {a.name}" for a, u in UNNAMED_CREATION_ABILITIES.items() if (a, u) not in made
    ):
        raise ValueError(f"the sweep did not see these make their unit type: {', '.join(unconfirmed)}")

    turned = {(performer, ability) for performer, ability, _, result in trials if result == "other"}
    offered: dict[UnitTypeId, set[AbilityId]] = {}
    for type_name, ability_names in _mapping(findings["offered"]).items():
        if (unit_type := _unit_type(type_name)) is not None:
            abilities = filter(None, map(_ability, _strings(ability_names)))
            offered[unit_type] = {ability for ability in abilities if (unit_type, ability) not in turned}

    needs: dict[tuple[UnitTypeId, AbilityId], TechRequirements] = {}
    for record in _records(findings["requirements"]):
        performer, ability = _unit_type(str(record["performer"])), _ability(str(record["ability"]))
        if performer is None or ability is None or ability not in offered.get(performer, ()):
            continue
        structures = frozenset(_required(_unit_type, record["structures"]))
        if any(_is_add_on(structure) for structure in structures) and not record["attached"]:
            raise ValueError(f"{performer.name} is offered {ability.name} with another structure's add-on")
        needs[performer, ability] = TechRequirements(structures, frozenset(_required(_upgrade, record["upgrades"])))
    pairs = [(unit, ability) for unit, abilities in offered.items() for ability in abilities]
    if unread := sorted(f"{unit.name} {ability.name}" for unit, ability in pairs if (unit, ability) not in needs):
        raise ValueError(f"what these need was never read: {', '.join(unread)}")

    creation_abilities = _creation_abilities(findings)
    return TechTree(
        base_build=int(str(findings["base_build"])),
        ability_requirements=MappingProxyType(
            {
                unit: MappingProxyType({ability: needs[unit, ability] for ability in abilities})
                for unit, abilities in offered.items()
            }
        ),
        ability_remaps=MappingProxyType(_remaps(findings)),
        ability_cancels=MappingProxyType(_cancels(findings)),
        creation_abilities=MappingProxyType(creation_abilities),
        ability_products=MappingProxyType(_products(creation_abilities, findings)),
        morph_sources=MappingProxyType(_morph_sources(trials)),
        # A pylon stands in its own field and needs no power, though the sweep once recorded one read as powered.
        power_consumers=frozenset(filter(None, map(_unit_type, _strings(findings["powered"])))) - {UnitTypeId.PYLON},
        unit_type_upgrades=MappingProxyType(
            {unit_type: MappingProxyType(upgrades) for unit_type, upgrades in found.unit_types.items()}
        ),
        upgrade_types=MappingProxyType(found.types),
        upgrade_levels=MappingProxyType(found.levels),
    )


@dataclass(frozen=True, slots=True)
class Upgrades:
    """What the upgrade sweep's findings say about what the curated ids name."""

    unit_types: dict[UnitTypeId, dict[UpgradeId, UnitTypeUpgrade]]
    """Every upgrade that affects each unit type, and what it adds to the type's row."""
    types: dict[UpgradeId, UpgradeType]
    """The kind each upgrade is: the upgrade level a unit reports it adds to."""
    levels: dict[UpgradeId, int]
    """Which level of its line each leveled upgrade is."""


def read_upgrades(upgrade_findings: Mapping[str, object]) -> Upgrades:
    """What each upgrade adds to each curated unit type, and which upgrade level units report it adds to.

    An upgrade affects a unit type where it changes the type's row or raises a level units of the type report, which
    the void ray's attack upgrades do though it has no weapon in the rows. An upgrade raising a level any unit reports
    is taken to raise it for every type whose row it changes, since a type the sweep put up none of reports nothing. A
    level is the number the curated name ends in, and an upgrade raising a report with no number is no level, as
    Chitinous Plating is.

    Raises `ValueError` where the sweep found something the changes do not account for, where one research finished
    more than one upgrade, where a change is to a weapon's attacks or cooldown, which the tables carry no change to,
    where an upgrade no curated id names affects a curated unit type, where one upgrade raises more than one kind of
    report, or where the levels of one kind affecting a type are not 1 onwards or add different amounts to it.
    """
    if unexplained := _strings(upgrade_findings["unexplained"]):
        raise ValueError(f"the changes do not account for: {'; '.join(unexplained)}")
    unit_types: defaultdict[UnitTypeId, dict[UpgradeId, UnitTypeUpgrade]] = defaultdict(dict)
    kinds: dict[UpgradeId, UpgradeType] = {}
    for record in _records(upgrade_findings["research"]):
        names = _strings(record["upgrades"])
        changes = _mapping(record["changes"])
        raised = {UpgradeType[kind.upper()]: _strings(types) for kind, types in _mapping(record["levels"]).items()}
        raised = {kind: types for kind, types in raised.items() if types}
        if len(names) != 1:
            if changes or raised:
                raise ValueError(f"one research finished {', '.join(names)}, which cannot be told apart")
            continue
        affected = {name for name in changes if _unit_type(name)} | {
            name for types in raised.values() for name in types if _unit_type(name)
        }
        if (upgrade := _upgrade(names[0])) is None:
            if affected:
                raise ValueError(f"{names[0]} affects {', '.join(sorted(affected))}, and no curated id names it")
            continue
        if len(raised) > 1:
            raise ValueError(
                f"{names[0]} raises the {' and '.join(sorted(k.name for k in raised))} levels units report"
            )
        if raised:
            kinds[upgrade] = next(iter(raised))
        for type_name in affected:
            change = _mapping(changes.get(type_name, {}))
            unit_types[_required_unit_type(type_name)][upgrade] = _unit_type_upgrade(names[0], type_name, change)
    levels = {upgrade: level for upgrade in kinds if (level := _level(upgrade))}
    for unit_type, upgrades in unit_types.items():
        for kind in UpgradeType:
            leveled = sorted((levels[u], u) for u in upgrades if kinds.get(u) is kind and u in levels)
            if [level for level, _ in leveled] != list(range(1, len(leveled) + 1)):
                raise ValueError(f"the {kind.name} levels affecting {unit_type.name} are not 1 onwards")
            if any(upgrades[u] != upgrades[leveled[0][1]] for _, u in leveled):
                raise ValueError(f"the {kind.name} levels of {unit_type.name} add different amounts")
    return Upgrades(dict(unit_types), kinds, levels)


def _level(upgrade: UpgradeId) -> int:
    """The number the curated name of `upgrade` ends in, or 0 where it ends in none."""
    last = upgrade.name.rsplit("_", 1)[-1]
    return int(last) if last.isdigit() else 0


def _required_unit_type(name: str) -> UnitTypeId:
    if (unit_type := _unit_type(name)) is None:
        raise ValueError(f"{name} is no curated unit type")
    return unit_type


def uncurated_upgraded(upgrade_findings: Mapping[str, object]) -> frozenset[str]:
    """The unit types upgrades change that no curated id names, in the raw catalog's spelling."""
    records = _records(upgrade_findings["research"])
    return frozenset(name for record in records for name in _mapping(record["changes"]) if _unit_type(name) is None)


def _unit_type_upgrade(upgrade: str, unit_type: str, change: Mapping[str, object]) -> UnitTypeUpgrade:
    """`change`, as the sweep writes it, as what the tables hold: a speed in distance per second of the game's Faster
    speed rather than its Normal one, as `UnitTypeData.speed` is."""
    weapons: list[WeaponUpgrade] = []
    for weapon in _records(change.get("weapons", [])):
        if "attacks" in weapon or "cooldown" in weapon:
            raise ValueError(f"{upgrade} changes the attacks or cooldown of a weapon of {unit_type}")
        bonuses = _mapping(weapon.get("bonuses", {}))
        weapons.append(
            WeaponUpgrade(
                damage=float(str(weapon.get("damage", 0.0))),
                damage_bonuses=MappingProxyType(
                    {Attribute[name.upper()]: float(str(bonus)) for name, bonus in bonuses.items()}
                ),
                range=float(str(weapon.get("range", 0.0))),
            )
        )
    # Rounded to what the game's 32-bit floats hold, which the conversion otherwise dresses up in digits of its own.
    speed = round(float(str(change.get("speed", 0.0))) * FASTER_PER_NORMAL_SPEED, 6)
    return UnitTypeUpgrade(armor=float(str(change.get("armor", 0.0))), speed=speed, weapons=tuple(weapons))


def uncurated(findings: Mapping[str, object]) -> frozenset[str]:
    """What the curated unit types are offered that no curated ability names, in the raw catalog's spelling."""
    offered = _mapping(findings["offered"]).items()
    names = (name for type_name, abilities in offered if _unit_type(type_name) for name in _strings(abilities))
    return frozenset(name for name in names if _ability(name) is None)


def _remaps(findings: Mapping[str, object]) -> dict[AbilityId, AbilityId]:
    """The general ability each ability stands for, as the game's table says, where the curated ids name both."""
    remaps = _mapping(findings["remaps"]).items()
    return {exact: general for e, g in remaps if (exact := _ability(e)) and (general := _ability(str(g)))}


def _cancels(findings: Mapping[str, object]) -> dict[AbilityId, AbilityId]:
    """The cancel a structure was offered for each thing it was set making, where the curated ids name both."""
    cancels = _mapping(findings["cancels"]).items()
    return {work: cancel for w, c in cancels if (work := _ability(w)) and (cancel := _ability(str(c)))}


def _creation_abilities(findings: Mapping[str, object]) -> dict[UnitTypeId, AbilityId]:
    """The ability that makes each unit type: what the game's table names where that works, and the unnamed creation
    ability where it does not, which there may be only one of."""
    named = {
        unit_type: ability
        for type_name, ability_name in _mapping(findings["creation_abilities"]).items()
        if (unit_type := _unit_type(type_name)) and (ability := _ability(str(ability_name)))
    }
    unnamed: defaultdict[UnitTypeId, set[AbilityId]] = defaultdict(set)
    for ability, unit_type in UNNAMED_CREATION_ABILITIES.items():
        if unit_type not in named:
            unnamed[unit_type].add(ability)
    if ambiguous := sorted(unit_type.name for unit_type, abilities in unnamed.items() if len(abilities) > 1):
        raise ValueError(f"the table names no working ability for these, and more than one is listed: {ambiguous}")
    return named | {unit_type: ability for unit_type, (ability,) in unnamed.items()}


def _products(
    creation_abilities: Mapping[UnitTypeId, AbilityId], findings: Mapping[str, object]
) -> dict[AbilityId, UnitTypeId | UpgradeId]:
    """The unit type or upgrade each ability makes, the unnamed creation abilities included, and the research
    abilities the table misnames. One sharing its ability with a type the game's table names it for, as a rich
    refinery shares the plain build with a refinery, leaves the table's product standing."""
    products: dict[AbilityId, UnitTypeId | UpgradeId] = {}
    for unit_type, ability in creation_abilities.items():
        if UNNAMED_CREATION_ABILITIES.get(ability) is not unit_type:
            products.setdefault(ability, unit_type)
    for ability, unit_type in UNNAMED_CREATION_ABILITIES.items():
        products.setdefault(ability, unit_type)
    for upgrade_name, ability_name in _mapping(findings["research_abilities"]).items():
        if (upgrade := _upgrade(upgrade_name)) and (ability := _ability(str(ability_name))):
            products[ability] = upgrade
    for upgrade, ability in MISNAMED_RESEARCH_ABILITIES.items():
        products[ability] = upgrade
    return products


def _morph_sources(trials: Iterable[Trial]) -> dict[UnitTypeId, UnitTypeId]:
    """The type each unit type is made out of, from the trials that used the unit ordered up.

    Where several types can be used up making one, it is the one the others are themselves made out of: an overseer is
    made out of an overlord, and out of the overlord transport an overlord becomes.
    """
    used_up: defaultdict[UnitTypeId, set[UnitTypeId]] = defaultdict(set)
    for performer, _, product, result in trials:
        if result == "morph":
            used_up[product].add(performer)
    sources: dict[UnitTypeId, UnitTypeId] = {}
    for product, performers in used_up.items():
        roots = [performer for performer in performers if not used_up.get(performer, set()) & performers]
        if len(roots) == 1:
            sources[product] = roots[0]
    return sources


def render(tech_tree: TechTree) -> str:
    """The module holding `tech_tree`."""
    return HEADER.format(base_build=tech_tree.base_build) + f"TECH_TREE: Final = {_literal(tech_tree, 0)}\n"


def output(tech_tree: TechTree) -> Path:
    """Where the module holding `tech_tree` goes."""
    return TECHTREE / f"_build_{tech_tree.base_build}.py"


def _literal(value: object, indent: int) -> str:
    """`value` as a Python expression starting at column `indent`: one member a line, each bracket beside the
    parenthesis it opens in, and what the tech tree holds for one ability on one line. `pyproject.toml` keeps the module
    out of ruff's formatter and its line length, which would undo both."""
    pad, inner = " " * indent, " " * (indent + 4)
    if isinstance(value, IntEnum | bool | int | float | tuple):
        return _inline(value)
    if isinstance(value, frozenset):
        if not value:
            return "frozenset()"
        members = "".join(f"{inner}{_literal(member, indent + 4)},\n" for member in sorted(value, key=_order))
        return f"frozenset({{\n{members}{pad}}})"
    if isinstance(value, Mapping):
        if not value:
            return "MappingProxyType({})"
        entries = sorted(value.items(), key=lambda entry: _order(entry[0]))
        lines = "".join(f"{inner}{_literal(k, indent + 4)}: {_literal(v, indent + 4)},\n" for k, v in entries)
        return f"MappingProxyType({{\n{lines}{pad}}})"
    if is_dataclass(value) and not isinstance(value, type):
        # What a class works out for itself is not given to it, and a default is left to it.
        given = [(field.name, getattr(value, field.name)) for field in fields(value) if field.init]
        given = [(name, member) for name, member in given if member != _default(value, name)]
        if indent:
            return _inline(value)
        lines = "".join(f"{inner}{name}={_literal(member, indent + 4)},\n" for name, member in given)
        return f"{type(value).__name__}(\n{lines}{pad})"
    raise TypeError(f"no literal for {value!r}")


def _inline(value: object) -> str:
    """`value` as a Python expression on one line."""
    if isinstance(value, IntEnum):
        return f"{type(value).__name__}.{value.name}"
    if isinstance(value, bool | int | float):
        return repr(value)
    if isinstance(value, frozenset):
        return (
            f"frozenset({{{', '.join(_inline(member) for member in sorted(value, key=_order))}}})"
            if value
            else "frozenset()"
        )
    if isinstance(value, tuple):
        members = ", ".join(_inline(member) for member in value)
        return f"({members},)" if len(value) == 1 else f"({members})"
    if isinstance(value, Mapping):
        entries = sorted(value.items(), key=lambda entry: _order(entry[0]))
        return f"MappingProxyType({{{', '.join(f'{_inline(k)}: {_inline(v)}' for k, v in entries)}}})"
    if is_dataclass(value) and not isinstance(value, type):
        given = [(field.name, getattr(value, field.name)) for field in fields(value) if field.init]
        given = [(name, member) for name, member in given if member != _default(value, name)]
        return f"{type(value).__name__}({', '.join(f'{name}={_inline(member)}' for name, member in given)})"
    raise TypeError(f"no literal for {value!r}")


def _default(value: object, name: str) -> object:
    """The default of the field `name` of the dataclass `value`, which no value equals where there is none."""
    field = next(field for field in fields(value) if field.name == name)  # type: ignore[arg-type]
    return field.default_factory() if field.default_factory is not MISSING else field.default


def _is_add_on(unit_type: UnitTypeId) -> bool:
    return "TECH_LAB" in unit_type.name or "REACTOR" in unit_type.name


def _order(value: object) -> str:
    return value.name if isinstance(value, IntEnum) else str(value)


def _trials(findings: Mapping[str, object]) -> list[Trial]:
    trials: list[Trial] = []
    for record in _records(findings["made"]):
        performer, ability = _unit_type(str(record["performer"])), _ability(str(record["ability"]))
        product = _unit_type(str(record["product"]))
        if performer is not None and ability is not None and product is not None:
            trials.append((performer, ability, product, str(record["result"])))
    return trials


def _unit_type(name: str) -> UnitTypeId | None:
    return UnitTypeId.get(RawUnitTypeId[name]) if name in RawUnitTypeId.__members__ else None


def _ability(name: str) -> AbilityId | None:
    return AbilityId.get(RawAbilityId[name]) if name in RawAbilityId.__members__ else None


def _upgrade(name: str) -> UpgradeId | None:
    return UpgradeId.get(RawUpgradeId[name]) if name in RawUpgradeId.__members__ else None


def _required[IdT](lookup: Callable[[str], IdT | None], names: object) -> Iterable[IdT]:
    """Each name curated, raising where one is not."""
    for name in _strings(names):
        if (member := lookup(name)) is None:
            raise ValueError(f"{name} is required, and no curated id names it")
        yield member


def _mapping(value: object) -> dict[str, object]:
    assert isinstance(value, dict)
    return {str(key): item for key, item in value.items()}


def _strings(value: object) -> list[str]:
    assert isinstance(value, list)
    return [str(item) for item in value]


def _records(value: object) -> list[dict[str, object]]:
    assert isinstance(value, list)
    return [_mapping(item) for item in value]


if __name__ == "__main__":
    findings = json.loads(INPUT.read_text(encoding="utf-8"))
    upgrade_findings = json.loads(UPGRADE_INPUT.read_text(encoding="utf-8"))
    tech_tree = read(findings, upgrade_findings)
    module = output(tech_tree)
    module.write_text(render(tech_tree), encoding="utf-8")
    print(f"{module.name}: {len(tech_tree.ability_requirements)} unit types, {len(tech_tree.morph_sources)} morphs")
    print(
        f"Upgrades affect {len(tech_tree.unit_type_upgrades)} unit types, and change"
        f" {len(uncurated_upgraded(upgrade_findings))} more no curated id names"
    )
    if f"from sc2nachos.gamedata._techtree.{module.stem} import" not in (TECHTREE / "__init__.py").read_text(
        encoding="utf-8"
    ):
        print(f"gamedata/_techtree/__init__.py does not import {module.stem} yet")
    print(f"{len(uncurated(findings))} abilities are offered that no curated id names")
