"""Generate `sc2nachos/units/_unit_type.py`: `UnitType`, with a class for every curated unit type and every group.

A type is in its race's group, and in `Structure` where the game's tables give it the structure attribute. A mineral
field, a geyser and a gas building are what the tables say holds minerals or vespene, of no race or of one; a worker
and a townhall are curated here. All are read from a corpus game's tables, so this runs without StarCraft II. Run it
again after changing `UnitTypeId`::

    uv run python tools/generate_unit_types.py
"""

from pathlib import Path

from sc2nachos.gamedata import Attribute, GameData, UnitTypeData
from sc2nachos.ids import UnitTypeId
from sc2nachos.match import Race
from sc2nachos.protocol import Recording

REPO = Path(__file__).parents[1]
CORPUS = REPO / "tests" / "corpus"
OUTPUT = REPO / "src" / "sc2nachos" / "units" / "_unit_type.py"

HEADER = '''"""Every type of unit, and the groups it is in, as classes for the type checker.

DO NOT EDIT. Generated by `tools/generate_unit_types.py`; run it again after changing `UnitTypeId`.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, ClassVar, Self, TypeGuard, cast, overload

from sc2nachos.ids import UnitTypeId

if TYPE_CHECKING:
    from sc2nachos.units._own_unit import OwnUnit
    from sc2nachos.units._unit import Unit


class UnitType:
    """Every type of unit, and every group of types, for the type checker. None is ever instantiated.

    `Unit[UnitType.Marine]` is a marine, and `Unit[UnitType.ProtossStructure]` a Protoss structure. A type's `id` is
    its `UnitTypeId`. A group is a race, the structures, or the structures of a race, as the game's tables give them;
    or the workers, the townhalls, the mineral fields, the vespene geysers or the gas buildings.
    """

    class AnyType:
        """Any type of unit, and what every type and group is.

        `type[UnitType.AnyType]` takes any of them. `Unit[Any]` is a unit that reads as any type, where
        `Unit[UnitType.AnyType]` is one whose type the type checker does not know, so a read only some types have is an
        error on it until `includes` narrows it.
        """

        _type_ids: ClassVar[frozenset[UnitTypeId]] = frozenset()

        def __init_subclass__(cls) -> None:
            """Add the type a class names by its `id` to every group it is in. A class without an `id` is a group."""
            super().__init_subclass__()
            type_id: UnitTypeId | None = cls.__dict__.get("id")
            cls._type_ids = frozenset() if type_id is None else frozenset((type_id,))
            if type_id is not None:
                # Everything between the class and `object` is a group it is in, `AnyType` included.
                for group in cast("tuple[type[UnitType.AnyType], ...]", cls.__mro__[1:-1]):
                    group._type_ids |= cls._type_ids

        @overload
        @classmethod
        def includes(cls, unit: OwnUnit[Any], /) -> TypeGuard[OwnUnit[Self]]: ...

        @overload
        @classmethod
        def includes(cls, unit: Unit[Any], /) -> TypeGuard[Unit[Self]]: ...

        @classmethod
        def includes(cls, unit: Unit[Any], /) -> bool:
            """Whether `unit` is of this type, or of a type in this group, narrowing it for the type checker.

            Raises `UncuratedIdError` for a unit of a type the curated ids leave out.
            """
            return unit.type_id in cls._type_ids
'''

# The races with a group of their own. A map's own units, such as mineral fields and rocks, have no race.
RACES = {Race.TERRAN: "Terran", Race.ZERG: "Zerg", Race.PROTOSS: "Protoss"}
# The workers and the townhalls, which the tables do not mark.
WORKERS = frozenset({UnitTypeId.SCV, UnitTypeId.PROBE, UnitTypeId.DRONE, UnitTypeId.DRONE_BURROWED})
TOWNHALLS = frozenset(
    {
        UnitTypeId.COMMAND_CENTER,
        UnitTypeId.COMMAND_CENTER_FLYING,
        UnitTypeId.ORBITAL_COMMAND,
        UnitTypeId.ORBITAL_COMMAND_FLYING,
        UnitTypeId.PLANETARY_FORTRESS,
        UnitTypeId.NEXUS,
        UnitTypeId.HATCHERY,
        UnitTypeId.LAIR,
        UnitTypeId.HIVE,
    }
)
# The groups of what a type is for, beside its race's, with their docstrings.
ROLES = {
    "Worker": "A worker: an SCV, a probe or a drone, burrowed or not. A MULE is none.",
    "Townhall": "A townhall: a command center or what it becomes, lifted or not, a nexus, a hatchery, lair or hive.",
    "AnyMineralField": "A mineral field of any kind: one the game's tables say holds minerals.",
    "AnyVespeneGeyser": "A vespene geyser of any kind: one the game's tables say holds vespene, of no race.",
    "GasBuilding": "A refinery, an assimilator or an extractor: one the game's tables say holds vespene, of a race.",
}


def class_name(unit_type: UnitTypeId) -> str:
    """The class name of a type: `SIEGE_TANK_SIEGED` is `SiegeTankSieged`."""
    return "".join(part.capitalize() for part in unit_type.name.split("_"))


def roles(unit_type: UnitTypeId, row: UnitTypeData) -> list[str]:
    """The groups of what `unit_type`, whose row is `row`, is for."""
    found = [role for role, members in (("Worker", WORKERS), ("Townhall", TOWNHALLS)) if unit_type in members]
    if row.has_minerals:
        found.append("AnyMineralField")
    if row.has_vespene:
        found.append("GasBuilding" if row.race in RACES else "AnyVespeneGeyser")
    return found


def render(tables: GameData) -> str:
    """The module source for the types in `tables`."""
    groups = {
        "Structure": ("AnyType", "A type the game's tables give the structure attribute."),
        **{name: ("AnyType", f"A {name} type.") for name in RACES.values()},
        **{f"{name}Structure": (f"{name}, Structure", f"A {name} structure.") for name in RACES.values()},
        **{role: ("AnyType", docstring) for role, docstring in ROLES.items()},
    }
    blocks = [HEADER]
    for name, (bases, docstring) in groups.items():
        blocks.append(f'    class {name}({bases}):\n        """{docstring}"""\n')
    names = set(groups)
    for unit_type in sorted(UnitTypeId, key=class_name):
        row = tables.units[unit_type]
        name = class_name(unit_type)
        if name in names:
            raise ValueError(f"{unit_type!r} would be named {name}, which is already taken")
        names.add(name)
        race = RACES.get(row.race)
        structure = Attribute.STRUCTURE in row.attributes
        base = f"{race}Structure" if race and structure else race or ("Structure" if structure else "AnyType")
        bases = ", ".join((base, *roles(unit_type, row)))
        blocks.append(f"    class {name}({bases}):\n        id = UnitTypeId.{unit_type.name}\n")
    return "\n".join(blocks)


def corpus_tables() -> GameData:
    """The tables of the first corpus game; every game on the current ladder shares them."""
    recording = Recording(sorted(CORPUS.glob("*.sc2rec"))[0])
    return GameData(next(exchange.response.data for exchange in recording if exchange.response.HasField("data")))


if __name__ == "__main__":
    OUTPUT.write_text(render(corpus_tables()), encoding="utf-8")
    print(f"{OUTPUT.name}: {len(UnitTypeId)} types")
